TARGET_KEYWORDS = {
    "it": [
        "it-компания",
        "ит-компания",
        "it компания",
        "аккредитованная it",
        "российский вендор",
        "b2b saas",
        "saas-платформ",
        "облачный провайдер",
        "облачная платформа",
        "кибербезопасност",
        # bigtech (дочки из других сфер отсекаются через INDUSTRY_EXCLUDES)
        "яндекс",
        "yandex",
        "вконтакте",
        "vk tech",
        "vk cloud",
        "касперск",
        "kaspersky",
        "positive technologies",
        "позитив текнолоджиз",
        "2гис",
        "2gis",
        # компании
        "yadro",
        "selectel",
        "селектел",
        "cloud.ru",
        "группа астра",
        "astra linux",
        "скб контур",
        "kontur",
        "ланит",
        "инфосистемы джет",
        "jet infosystems",
        "huawei",
    ],
    "healthtech": [
        "healthtech",
        "health tech",
        "digital health",
        "digital healthcare",
        "медицина",
        "медицин",
        "здравоохран",
        "healthcare",
        "телемедицин",
        "клиник",
        "аптек",
        # компании
        "сберздоровье",
        "сбер здоровье",
        "еаптека",
        "аптека.ру",
        "инвитро",
        "invitro",
        "гемотест",
        "медси",
        "доктор рядом",
        "хеликс",
        "будь здоров",
        "докдок",
        "docdoc",
        "цифромед",
    ],
    "medtech": [
        "medtech",
        "med tech",
        "медтех",
        "медицинское оборудование",
        "medical device",
        "медицинские изделия",
        "лучевая диагностика",
        # компании
        "цельс",
        "celsus",
        "botkin.ai",
        "боткин.ai",
        "третье мнение",
        "webiomed",
        "вебиомед",
        "спутник медтех",
        "мед-ай",
    ],
    "femtech": [
        "femtech",
        "женское здоровье",
        "women's health",
        "women health",
        "fertility",
        "репродуктив",
        "гинеколог",
        "эко-клиник",
        # компании
        "flo health",
        "клиника фомина",
        "мать и дитя",
        "next generation",
        "нова клиник",
        "эмбрилайф",
    ],
    "fintech": [
        "fintech",
        "финтех",
        "финансовые технологии",
        "платежный сервис",
        "платежные системы",
        "payments",
        "банкинг",
        "страхование",
        "банковск",
        "необанк",
        "кредитн",
        "скоринг",
        "эквайринг",
        "антифрод",
        "брокерск",
        "сбер",
        "втб",
        "т-банк",
        "тинькофф",
        "альфа-банк",
        "альфа банк",
        "газпромбанк",
        "россельхозбанк",
        "райффайзен",
        "совкомбанк",
        "росбанк",
        "промсвязьбанк",
        "мтс банк",
        "почта банк",
        "модульбанк",
        "юникредит",
        "уралсиб",
        "хоум кредит",
        "яндекс пэй",
        "юкасса",
        "юmoney",
        "qiwi",
        "киви",
        "росгосстрах",
        "ингосстрах",
        "ренессанс страхование",
        "согаз",
        "альфастрахование",
        "мосбиржа",
        "московская биржа",
        "бкс",
        "финам",
        "цифра брокер",
        "псб",
        "dsk bank",
        "(банк)",
    ],
    "edtech": [
        "edtech",
        "эдтех",
        "образовательные технологии",
        "онлайн-образование",
        "online education",
        "education",
        "онлайн-школа",
        "онлайн школа",
        # компании
        "skillbox",
        "скиллбокс",
        "нетология",
        "skyeng",
        "скайэнг",
        "яндекс практикум",
        "geekbrains",
        "гикбреинс",
        "учи.ру",
        "фоксфорд",
        "stepik",
        "степик",
        "синергия",
        "skillfactory",
        "skypro",
        "мaximum education",
        "тетрика",
    ],
    "hrtech": [
        "hrtech",
        "hr tech",
        "hr-tech",
        "кадровые технологии",
        "recruiting tech",
        "подбор персонала",
        "рекрутинг",
        # компании
        "хедхантер",
        "headhunter",
        "hh.ru",
        "superjob",
        "суперджоб",
        "работа.ру",
        "хантфлоу",
        "huntflow",
        "skillaz",
        "скиллаз",
        "potok.io",
        "сбер подбор",
        "talantix",
        "талантикс",
    ],
    "adtech": [
        "adtech",
        "ad tech",
        "martech",
        "mar tech",
        "рекламные технологии",
        "programmatic",
        "рекламная платформа",
        "рекламная сеть",
        "перформанс-маркетинг",
        "dsp-платформ",
        "dmp-платформ",
        "яндекс директ",
        "vk реклама",
        "vk ads",
        "mytarget",
        "майтаргет",
        "adfox",
        "adriver",
        "relap",
        "getintent",
        "soloway",
        "weborama",
        "sber ads",
        "сберадс",
        "roistat",
        "ройстат",
    ],
    "gamedev": [
        "gamedev",
        "game dev",
        "геймдев",
        "игровая индустрия",
        "games industry",
        "мобильные игры",
        "игровая студия",
        # компании
        "playrix",
        "плэйрикс",
        "wargaming",
        "pixonic",
        "пиксоник",
        "my.games",
        "vk play",
        "nexters",
        "belka games",
        "astrum",
        "game insight",
        "battlestate",
        "owlcat",
        "1c game studios",
    ],
    "logistics": [
        "logistics",
        "логистика",
        "логистическая",
        "supply chain",
        "cargo",
        "delivery tech",
        "грузоперевозк",
        "последняя миля",
        "складская",
        "цепочк поставок",
        # компании
        "сдэк",
        "cdek",
        "деловые линии",
        "boxberry",
        "боксберри",
        "пэк",
        "почта россии",
        "яндекс доставка",
        "достависта",
        "монополия",
        "фм ложистик",
        "x5 транспорт",
        "везёт всем",
    ],
    "ecommerce": [
        "e-commerce",
        "ecommerce",
        "интернет-магазин",
        "интернет магазин",
        "маркетплейс",
        "marketplace",
        "онлайн-ритейл",
        "online retail",
        "фудтех",
        "foodtech",
        "ozon",
        "озон",
        "wildberries",
        "вайлдберриз",
        "авито",
        "avito",
        "золотое яблоко",
        "lamoda",
        "ламода",
        "детский мир",
        "мвидео",
        "м.видео",
        "яндекс маркет",
        "сбермаркет",
        "сбермегамаркет",
        "самокат",
        "вкусвилл",
        "x5 group",
        "пятёрочка",
        "магнит",
        "лента ритейл",
        "додо",
        "delivery club",
        "яндекс еда",
        "купер",
    ],
    "telecom": [
        "телекоммуникац",
        "оператор связи",
        "сотовая связь",
        "мобильный оператор",
        "виртуальный оператор",
        "voip",
        "мтс",
        "мегафон",
        "билайн",
        "beeline",
        "теле2",
        "tele2",
        "ростелеком",
        "транстелеком",
        "эр-телеком",
        "дом.ру",
    ],
    "media": [
        "медиахолдинг",
        "медиасервис",
        "media holding",
        "онлайн-кинотеатр",
        "видеосервис",
        "видеостриминг",
        "стриминговый сервис",
        "видеохостинг",
        "издательство",
        "подкаст",
        "ivi",
        "окко",
        "okko",
        "кинопоиск",
        "premier.one",
        "wink",
        "rutube",
        "рутуб",
        "vk видео",
        "старт.ру",
        "яндекс музыка",
        "звук бизнес",
        "литрес",
        "нетфликс",
        "netflix",
    ],
    "govtech": [
        "govtech",
        "госсектор",
        "госуслуг",
        "цифровое правительство",
        "электронное правительство",
        "минцифр",
        # компании / ведомства
        "гнивц",
        "фнс",
        "налоговой службы",
    ],
    "traveltech": [
        "traveltech",
        "тревелтех",
        "туристическ",
        "авиабилет",
        "бронирование отелей",
        # компании
        "авиасейлс",
        "aviasales",
        "туту.ру",
        "tutu.ru",
        "островок",
        "ostrovok",
        "яндекс путешествия",
        "аэрофлот",
    ],
    "cybersecurity": [
        "кибербезопасност",
        "cybersecurity",
        "cyber security",
        "антивирус",
        # компании
        "f6",
        "group-ib",
        "positive technologies",
        "лаборатория касперского",
        "kaspersky",
        "bi.zone",
        "ростелеком-солар",
        "инфотекс",
    ],
}

INDUSTRY_LABELS = {
    "it": "IT / Bigtech",
    "healthtech": "Healthtech",
    "medtech": "Medtech",
    "femtech": "Femtech",
    "fintech": "Fintech",
    "edtech": "Edtech",
    "hrtech": "HRtech",
    "adtech": "Adtech/Martech",
    "gamedev": "Gamedev",
    "logistics": "Логистика",
    "ecommerce": "E-commerce",
    "telecom": "Телеком",
    "media": "Медиа",
    "govtech": "Госсектор",
    "traveltech": "Traveltech",
    "cybersecurity": "Кибербезопасность",
}

# фразы, которые не считаются попаданием в сферу. если фраза есть в company/title —
# вакансия целиком не из этой сферы (дочка bigtech), если только в описании —
# фраза вырезается из текста, остальные ключевые слова продолжают работать
INDUSTRY_EXCLUDES = {
    "it": [
        "яндекс маркет",
        "yandex market",
        "яндекс еда",
        "yandex eats",
        "яндекс лавка",
        "яндекс доставка",
        "yandex delivery",
        "яндекс go",
        "яндекс такси",
        "yandex taxi",
        "яндекс пэй",
        "yandex pay",
        "яндекс банк",
        "яндекс практикум",
        "яндекс директ",
        "яндекс музыка",
        "яндекс афиша",
        "яндекс путешествия",
    ],
}

# человекочитаемые названия сфер — используются и в кнопках бота,
# и в подписи сводки. порядок словаря = порядок кнопок в /industries
ROLE_TAXONOMY = {
    "data_scientist": [
        "data scientist",
        "дата-сайентист",
        "дата саентист",
        "дата сайентист",
        "исследователь данных",
    ],
    "ml_engineer": [
        "ml engineer",
        "ml-инженер",
        "ml инженер",
        "machine learning engineer",
        "machine-learning engineer",
        "инженер машинного обучения",
        "мо-инженер",
        "мо инженер",
        "инженер мо",
        "mle",
        "ml-разработчик",
        "ml разработчик",
        "ml developer",
    ],
    "ai_engineer": [
        "ai engineer",
        "ai/ml",
    ],
    "dl_engineer": [
        "deep learning engineer",
        "deep-learning engineer",
        "deep learning developer",
        "dl engineer",
        "dl-инженер",
        "dl инженер",
        "dl developer",
        "dl-разработчик",
        "dl разработчик",
        "инженер глубокого обучения",
    ],
    "data_governance": [
        "data governance analyst",
        "data governance specialist",
        "специалист по управлению данными",
        "аналитик по управлению данными",
        "data governance engineer",
    ],
    "data_quality": [
        "data steward",
        "дата стюард",
        "дата-стюард",
        "стюард данных",
        "data quality analyst",
        "data quality engineer",
        "data quality specialist",
        "специалист по качеству данных",
        "аналитик по качеству данных",
        "инженер по качеству данных",
    ],
    "research_scientist": [
        "research scientist",
        "researcher in ai",
        "researcher in ml",
    ],
    "nlp_engineer": [
        "nlp engineer",
        "nlp",
        "нлп инженер",
        "nlp инженер",
    ],
    "cv_engineer": [
        "cv engineer",
        "computer vision engineer",
        "computer-vision engineer",
        "инженер компьютерного зрения",
        "cv-инженер",
        "cv инженер",
    ],
    "data_analyst": [
        "data analyst",
        "дата аналитик",
        "дата-аналитик",
        "аналитик данных",
    ],
    "data_engineer": [
        "data engineer",
        "дата инженер",
        "дата-инженер",
        "инженер данных",
        "data engineering",
        "data_platform_engineer",
    ],
    "mlops_engineer": [
        "mlops",
        "ml ops",
        "mlops engineer",
        "mlops-инженер",
    ],
}

ROLE_LABELS = {
    "data_scientist": "Data Scientist",
    "ml_engineer": "ML Engineer",
    "ai_ml_engineer": "AI/ML Engineer",
    "dl_engineer": "DL Engineer",
    "data_engineer": "Data Engineer",
    "data_analyst": "Data Analyst",
    "cv_engineer": "CV Engineer",
    "nlp_engineer": "NLP Engineer",
    "research_scientist": "Research Scientist",
    "data_governance": "Data Governance",
    "data_quality": "Data Quality",
    "mlops_engineer": "MLOps Engineer",
}

EXCLUDED_ROLES = [
    "frontend",
    "backend",
    "fullstack",
    "full-stack",
    "android",
    "ios",
    "game designer",
    "game developer",
    "devops",
    "qa",
    "qa engineer",
    "ui/ux",
    "ux/ui",
    "content manager",
]

LEVEL_TAXONOMY = {
    "Стажер": [
        "стажер",
        "стажёр",
        "стажировка",
        "intern",
        "internship",
        "trainee",
    ],
    "Джуниор": [
        "junior",
        "джуниор",
        "джун",
        "младший",
    ],
    "Миддл": [
        "middle",
        "миддл",
        "мидл",
    ],
    "Сеньор": [
        "senior",
        "сеньор",
        "синьор",
        "старший",
        "ведущий",
        "principal",
        "staff",
    ],
    "Тимлид/Руководитель группы": [
        "team lead",
        "tech lead",
        "техлид",
        "тимлид",
        "руководитель группы",
        "руководитель команды",
        "lead",
    ],
    "Руководитель отдела/подразделения": [
        "head of",
        "руководитель отдела",
        "руководитель направления",
        "руководитель департамента",
        "начальник отдела",
        "engineering manager",
    ],
    "Директор": [
        "директор",
        "director",
        "cto",
        "cio",
        "ciso",
        "cmo",
        "cdo",
        "chief",
        "ceo",
    ],
    "VP": [
        "vp",
        "vice president",
        "вице-президент",
    ],
    "Архитектор": [
        "архитектор",
        "architect",
    ],
    "Консультант": [
        "консультант",
        "consultant",
    ],
}


# базовый словарь технологий/скиллов для поиска в тексте описания вакансии
# (пополняется по мере находок — сейчас взят из реальных skills_objects getmatch)
SKILLS_VOCABULARY = [
    "python",
    "java",
    "kotlin",
    "go",
    "golang",
    "c++",
    "c#",
    ".net",
    "javascript",
    "typescript",
    "php",
    "ruby",
    "scala",
    "rust",
    "sql",
    "postgresql",
    "mysql",
    "clickhouse",
    "mongodb",
    "redis",
    "kafka",
    "rabbitmq",
    "airflow",
    "pandas",
    "numpy",
    "pytorch",
    "tensorflow",
    "scikit-learn",
    "sklearn",
    "catboost",
    "xgboost",
    "lightgbm",
    "docker",
    "kubernetes",
    "ci/cd",
    "linux",
    "grafana",
    "prometheus",
    "aws",
    "gcp",
    "azure",
    "nlp",
    "llm",
    "rag",
    "computer vision",
    "deep learning",
    "machine learning",
    "data science",
    "react",
    "vue",
    "angular",
    "flutter",
    "kotlin multiplatform",
    "hadoop",
    "spark",
    "hive",
]
